name: many_lints
description: "A comprehensive collection of custom lint rules, quick fixes, and code assists for Flutter and Dart projects."
version: 0.3.0
homepage: https://github.com/Nikoro/many_lints
repository: https://github.com/Nikoro/many_lints
issue_tracker: https://github.com/Nikoro/many_lints/issues
topics: [lint, lints, linter, analyzer, code]

environment:
  sdk: ^3.10.0

dependencies:
  analyzer: ^10.0.2
  analyzer_plugin: ^0.14.2
  analysis_server_plugin: ^0.3.8

dev_dependencies:
  test: ^1.29.0
  analyzer_testing: ^0.1.10
  test_reflective_loader: ^0.4.0
  lints: ^6.1.0
